### ISSUE TITLE
Change package.json to specify explicit node-sass version

### ISSUE THREAD

**Issue by bryanerayner** [sindresorhus/grunt-sass#258] opened 2015-11-09 15:38 UTC
I recently ran into an issue in our code base related to your plugin. We all work on different machines, in different countries. It is common for different members of our team to update our node packages at different times, sometimes months apart.

Since your package depends on `node-sass: "^3.0.0",` instead of a specific version, we recently encountered breaking changes in our build process. We did a fresh npm install on our build servers, and since your package does not specify a specific version of node-sass, we got a version which introduced the breaking changes.

I am resolving this by specifying a specific `node-sass` in our `package.json`, but it would be nice if other projects did not encounter this problem in the future.

Would you be able to commit to releasing package updates mirroring `node-sass` releases, so that projects dependent on your plugin will not run into this problem unexpectedly?

**Comment by sindresorhus** [comment] 2015-11-09 15:48
Duplicate of https://github.com/sindresorhus/grunt-sass/issues/255. This is how all npm packages work. It's up to you to ensure consistency on your part by using shrinkwrap.

**Closed by sindresorhus** 2015-11-09 15:48 UTC

**Comment by bryanerayner** [comment] 2015-11-10 16:47
I was unaware of shrinkwrap. Thanks!
