### ISSUE TITLE
error: Failed to start an Appium session, err was: TypeError: Arguments to path.resolve must be strings

### ISSUE THREAD

**Issue by rockyav** [sindresorhus/grunt-sass#218] opened 2015-06-12 10:03 UTC
Hi Guys,

After start Appium by command :
 - appium --command-timeout 120 -g /path/appium.log -U UDID -p 8723

I ran the test case:
- pybot --variable DEVICE_NAME:iPhone5Aa -L DEBUG /path/testcase.txt 

I got error:

WARN Finding XcodePath by symlink because TypeError: Invalid attempt to destructure non-iterable instance 
error: Arguments to path.resolve must be strings
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] On a real device; cannot clean device state
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: TypeError: Arguments to path.resolve must be strings
info: [debug] TypeError: Arguments to path.resolve must be strings
    at Object.posix.resolve (path.js:439:13)
    at getVersionWithoutRetry$ (lib/xcode.js:112:26)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/appium-xcode/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/appium-xcode/node_modules/babel-runtime/regenerator/runtime.js:294:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/appium-xcode/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/appium-xcode/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at bound (domain.js:254:14)
    at runBound (domain.js:267:12)
    at /usr/local/lib/node_modules/appium/node_modules/appium-xcode/node_modules/babel-runtime/regenerator/runtime.js:165:16
    at runMicrotasksCallback (node.js:337:7)
    at process._tickDomainCallback (node.js:381:11)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Arguments to path.resolve must be strings)","origValue":"Arguments to path.resolve must be strings"},"sessionId":null}

Would you please help me to resolve this issue ? or explain for me about this issue ?

Thank you so much,
VuNguyen

**Comment by sindresorhus** [comment] 2015-06-12 10:09
Duplicate of #217. Open an issue on `node-sass`. https://github.com/sass/node-sass/issues/new

**Closed by sindresorhus** 2015-06-12 10:09 UTC

**Comment by rockyav** [comment] 2015-06-12 10:50
@sindresorhus Would you please advise me about this issue ? 
It's related node-sass ?

**Comment by sindresorhus** [comment] 2015-06-12 14:36
Yes

**Comment by derek1106** [comment] 2015-06-24 22:15
Why this issue is closed? It didn't provide the way to fix the issue.
